project:
  type: book
  output-dir: docs

book:
  title: "Introduction to data analysis and visualization with R"
  author: "György Barabás"
  chapters:
    - index.qmd
    - Intro_R_RStudio.qmd
    - R_programming_basics.qmd
    - Data_reading.qmd
    - Basic_data_wrangling.qmd
    - Summaries_normalization.qmd
    - Creating_figures.qmd
    - Further_plotting_options.qmd
    - Joining_data.qmd
    - Intro_statistics.qmd
    - References.qmd

bibliography: biblio.bib

format:
  html:
    theme: cosmo
    toc-depth: 3
    number-depth: 3
